[ L
    ( Position 1 1 )
    ( Indent 0 )
, L
    ( Position 1 1 )
    ( TokSym "name" )
, L
    ( Position 1 5 ) Colon
, L
    ( Position 1 22 )
    ( TokSym "dockerfile" )
, L
    ( Position 2 1 )
    ( Indent 0 )
, L
    ( Position 2 1 )
    ( TokSym "version" )
, L
    ( Position 2 8 ) Colon
, L
    ( Position 2 22 )
    ( TokSym "0.1.0.0" )
, L
    ( Position 3 1 )
    ( Indent 0 )
, L
    ( Position 3 1 )
    ( TokSym "synopsis" )
, L
    ( Position 3 9 ) Colon
, L
    ( Position 3 22 )
    ( TokSym "Type-safe" )
, L
    ( Position 3 32 )
    ( TokSym "composable" )
, L
    ( Position 3 43 )
    ( TokSym "Dockerfile" )
, L
    ( Position 3 54 )
    ( TokSym "generator" )
, L
    ( Position 3 64 )
    ( TokSym "and" )
, L
    ( Position 3 68 )
    ( TokSym "parsers." )
, L
    ( Position 4 1 )
    ( Indent 0 )
, L
    ( Position 4 1 )
    ( TokSym "description" )
, L
    ( Position 4 12 ) Colon
, L
    ( Position 4 22 )
    ( TokSym "Describe" )
, L
    ( Position 4 31 )
    ( TokSym "Dockerfile" )
, L
    ( Position 4 42 )
    ( TokSym "containers" )
, L
    ( Position 4 53 )
    ( TokSym "in" )
, L
    ( Position 4 56 )
    ( TokSym "Haskell." )
, L
    ( Position 5 1 )
    ( Indent 0 )
, L
    ( Position 5 1 )
    ( TokSym "license" )
, L
    ( Position 5 8 ) Colon
, L
    ( Position 5 22 )
    ( TokSym "MIT" )
, L
    ( Position 6 1 )
    ( Indent 0 )
, L
    ( Position 6 1 )
    ( TokSym "license-file" )
, L
    ( Position 6 13 ) Colon
, L
    ( Position 6 22 )
    ( TokSym "LICENSE" )
, L
    ( Position 7 1 )
    ( Indent 0 )
, L
    ( Position 7 1 )
    ( TokSym "author" )
, L
    ( Position 7 7 ) Colon
, L
    ( Position 7 22 )
    ( TokSym "Christopher" )
, L
    ( Position 7 34 )
    ( TokSym "Reichert" )
, L
    ( Position 8 1 )
    ( Indent 0 )
, L
    ( Position 8 1 )
    ( TokSym "maintainer" )
, L
    ( Position 8 11 ) Colon
, L
    ( Position 8 22 )
    ( TokSym "creichert07" )
, L
    ( Position 8 33 )
    ( TokOther "@" )
, L
    ( Position 8 34 )
    ( TokSym "gmail.com" )
, L
    ( Position 9 1 )
    ( Indent 0 )
, L
    ( Position 9 1 )
    ( TokSym "copyright" )
, L
    ( Position 9 10 ) Colon
, L
    ( Position 9 22 )
    ( TokOther "(" )
, L
    ( Position 9 23 )
    ( TokSym "c" )
, L
    ( Position 9 24 )
    ( TokOther ")" )
, L
    ( Position 9 26 )
    ( TokSym "2015" )
, L
    ( Position 9 31 )
    ( TokSym "Christopher" )
, L
    ( Position 9 43 )
    ( TokSym "Reichert" )
, L
    ( Position 9 52 )
    ( TokOther "<" )
, L
    ( Position 9 53 )
    ( TokSym "creichert07" )
, L
    ( Position 9 64 )
    ( TokOther "@" )
, L
    ( Position 9 65 )
    ( TokSym "gmail.com" )
, L
    ( Position 9 74 )
    ( TokOther ">" )
, L
    ( Position 10 1 )
    ( Indent 0 )
, L
    ( Position 10 1 )
    ( TokSym "category" )
, L
    ( Position 10 9 ) Colon
, L
    ( Position 10 22 )
    ( TokSym "Data" )
, L
    ( Position 11 1 )
    ( Indent 0 )
, L
    ( Position 11 1 )
    ( TokSym "build-type" )
, L
    ( Position 11 11 ) Colon
, L
    ( Position 11 22 )
    ( TokSym "Simple" )
, L
    ( Position 12 1 )
    ( Indent 0 )
, L
    ( Position 12 1 )
    ( TokSym "cabal-version" )
, L
    ( Position 12 14 ) Colon
, L
    ( Position 12 22 )
    ( TokOther ">=" )
, L
    ( Position 12 24 )
    ( TokSym "1.10" )
, L
    ( Position 14 1 )
    ( Indent 0 )
, L
    ( Position 14 1 )
    ( TokSym "library" )
, L
    ( Position 15 1 )
    ( Indent 2 )
, L
    ( Position 15 3 )
    ( TokSym "exposed-modules" )
, L
    ( Position 15 18 ) Colon
, L
    ( Position 15 24 )
    ( TokSym "Data.Docker" )
, L
    ( Position 16 1 )
    ( Indent 2 )
, L
    ( Position 16 3 )
    ( TokSym "other-extensions" )
, L
    ( Position 16 19 ) Colon
, L
    ( Position 16 24 )
    ( TokSym "OverloadedStrings" )
, L
    ( Position 17 1 )
    ( Indent 2 )
, L
    ( Position 17 3 )
    ( TokSym "build-depends" )
, L
    ( Position 17 16 ) Colon
, L
    ( Position 17 24 )
    ( TokSym "base" )
, L
    ( Position 17 29 )
    ( TokOther "==" )
, L
    ( Position 17 32 )
    ( TokSym "4." )
, L
    ( Position 17 34 )
    ( TokOther "*" )
, L
    ( Position 18 1 )
    ( Indent 2 )
, L
    ( Position 18 3 )
    ( TokSym "default-language" )
, L
    ( Position 18 19 ) Colon
, L
    ( Position 18 24 )
    ( TokSym "Haskell2010" )
, L
    ( Position 20 1 )
    ( Indent 0 )
, L
    ( Position 20 1 )
    ( TokSym "test-suite" )
, L
    ( Position 20 12 )
    ( TokSym "spec" )
, L
    ( Position 21 1 )
    ( Indent 2 )
, L
    ( Position 21 3 )
    ( TokSym "build-depends" )
, L
    ( Position 21 16 ) Colon
, L
    ( Position 21 19 )
    ( TokSym "base" )
, L
    ( Position 21 24 )
    ( TokOther "==" )
, L
    ( Position 21 27 )
    ( TokSym "4." )
, L
    ( Position 21 29 )
    ( TokOther "*," )
, L
    ( Position 21 32 )
    ( TokSym "dockerfile" )
, L
    ( Position 21 42 )
    ( TokOther "," )
, L
    ( Position 21 44 )
    ( TokSym "hspec" )
, L
    ( Position 22 1 )
    ( Indent 2 )
, L
    ( Position 22 3 )
    ( TokSym "ghc-options" )
, L
    ( Position 22 14 ) Colon
, L
    ( Position 22 19 )
    ( TokSym "-Wall" )
, L
    ( Position 23 1 )
    ( Indent 2 )
, L
    ( Position 23 3 )
    ( TokSym "type" )
, L
    ( Position 23 7 ) Colon
, L
    ( Position 23 19 )
    ( TokSym "exitcode-stdio-1.0" )
, L
    ( Position 24 1 )
    ( Indent 2 )
, L
    ( Position 24 3 )
    ( TokSym "hs-source-dirs" )
, L
    ( Position 24 17 ) Colon
, L
    ( Position 24 19 )
    ( TokSym "test" )
, L
    ( Position 25 1 )
    ( Indent 2 )
, L
    ( Position 25 3 )
    ( TokSym "main-is" )
, L
    ( Position 25 10 ) Colon
, L
    ( Position 25 19 )
    ( TokSym "Spec.hs" )
, L
    ( Position 25 26 ) EOF
]
