[ L
    ( Position 7 1 )
    ( Indent 0 )
, L
    ( Position 7 1 )
    ( TokSym "name" )
, L
    ( Position 7 5 ) Colon
, L
    ( Position 7 17 )
    ( TokSym "dockerfile" )
, L
    ( Position 8 1 )
    ( Indent 0 )
, L
    ( Position 8 1 )
    ( TokSym "version" )
, L
    ( Position 8 8 ) Colon
, L
    ( Position 8 17 )
    ( TokSym "0.2.0" )
, L
    ( Position 9 1 )
    ( Indent 0 )
, L
    ( Position 9 1 )
    ( TokSym "synopsis" )
, L
    ( Position 9 9 ) Colon
, L
    ( Position 9 17 )
    ( TokSym "A" )
, L
    ( Position 9 19 )
    ( TokSym "Haskell" )
, L
    ( Position 9 27 )
    ( TokSym "DSL" )
, L
    ( Position 9 31 )
    ( TokSym "for" )
, L
    ( Position 9 35 )
    ( TokSym "generating" )
, L
    ( Position 9 46 )
    ( TokSym "Dockerfiles" )
, L
    ( Position 10 1 )
    ( Indent 0 )
, L
    ( Position 10 1 )
    ( TokSym "category" )
, L
    ( Position 10 9 ) Colon
, L
    ( Position 10 17 )
    ( TokSym "Data" )
, L
    ( Position 11 1 )
    ( Indent 0 )
, L
    ( Position 11 1 )
    ( TokSym "homepage" )
, L
    ( Position 11 9 ) Colon
, L
    ( Position 11 17 )
    ( TokSym "https" )
, L
    ( Position 11 22 ) Colon
, L
    ( Position 11 23 )
    ( TokOther "//" )
, L
    ( Position 11 25 )
    ( TokSym "github.com" )
, L
    ( Position 11 35 )
    ( TokOther "/" )
, L
    ( Position 11 36 )
    ( TokSym "creichert" )
, L
    ( Position 11 45 )
    ( TokOther "/" )
, L
    ( Position 11 46 )
    ( TokSym "dockerfile" )
, L
    ( Position 11 56 )
    ( TokOther "#" )
, L
    ( Position 11 57 )
    ( TokSym "readme" )
, L
    ( Position 12 1 )
    ( Indent 0 )
, L
    ( Position 12 1 )
    ( TokSym "bug-reports" )
, L
    ( Position 12 12 ) Colon
, L
    ( Position 12 17 )
    ( TokSym "https" )
, L
    ( Position 12 22 ) Colon
, L
    ( Position 12 23 )
    ( TokOther "//" )
, L
    ( Position 12 25 )
    ( TokSym "github.com" )
, L
    ( Position 12 35 )
    ( TokOther "/" )
, L
    ( Position 12 36 )
    ( TokSym "creichert" )
, L
    ( Position 12 45 )
    ( TokOther "/" )
, L
    ( Position 12 46 )
    ( TokSym "dockerfile" )
, L
    ( Position 12 56 )
    ( TokOther "/" )
, L
    ( Position 12 57 )
    ( TokSym "issues" )
, L
    ( Position 13 1 )
    ( Indent 0 )
, L
    ( Position 13 1 )
    ( TokSym "author" )
, L
    ( Position 13 7 ) Colon
, L
    ( Position 13 17 )
    ( TokSym "Christopher" )
, L
    ( Position 13 29 )
    ( TokSym "Reichert" )
, L
    ( Position 14 1 )
    ( Indent 0 )
, L
    ( Position 14 1 )
    ( TokSym "maintainer" )
, L
    ( Position 14 11 ) Colon
, L
    ( Position 14 17 )
    ( TokSym "creichert07" )
, L
    ( Position 14 28 )
    ( TokOther "@" )
, L
    ( Position 14 29 )
    ( TokSym "gmail.com" )
, L
    ( Position 15 1 )
    ( Indent 0 )
, L
    ( Position 15 1 )
    ( TokSym "copyright" )
, L
    ( Position 15 10 ) Colon
, L
    ( Position 15 17 )
    ( TokOther "(" )
, L
    ( Position 15 18 )
    ( TokSym "c" )
, L
    ( Position 15 19 )
    ( TokOther ")" )
, L
    ( Position 15 21 )
    ( TokSym "2018" )
, L
    ( Position 15 26 )
    ( TokSym "Christopher" )
, L
    ( Position 15 38 )
    ( TokSym "Reichert" )
, L
    ( Position 15 47 )
    ( TokOther "<" )
, L
    ( Position 15 48 )
    ( TokSym "creichert07" )
, L
    ( Position 15 59 )
    ( TokOther "@" )
, L
    ( Position 15 60 )
    ( TokSym "gmail.com" )
, L
    ( Position 15 69 )
    ( TokOther ">" )
, L
    ( Position 16 1 )
    ( Indent 0 )
, L
    ( Position 16 1 )
    ( TokSym "license" )
, L
    ( Position 16 8 ) Colon
, L
    ( Position 16 17 )
    ( TokSym "MIT" )
, L
    ( Position 17 1 )
    ( Indent 0 )
, L
    ( Position 17 1 )
    ( TokSym "license-file" )
, L
    ( Position 17 13 ) Colon
, L
    ( Position 17 17 )
    ( TokSym "LICENSE" )
, L
    ( Position 18 1 )
    ( Indent 0 )
, L
    ( Position 18 1 )
    ( TokSym "build-type" )
, L
    ( Position 18 11 ) Colon
, L
    ( Position 18 17 )
    ( TokSym "Simple" )
, L
    ( Position 19 1 )
    ( Indent 0 )
, L
    ( Position 19 1 )
    ( TokSym "cabal-version" )
, L
    ( Position 19 14 ) Colon
, L
    ( Position 19 17 )
    ( TokOther ">=" )
, L
    ( Position 19 20 )
    ( TokSym "1.10" )
, L
    ( Position 21 1 )
    ( Indent 0 )
, L
    ( Position 21 1 )
    ( TokSym "source-repository" )
, L
    ( Position 21 19 )
    ( TokSym "head" )
, L
    ( Position 22 1 )
    ( Indent 2 )
, L
    ( Position 22 3 )
    ( TokSym "type" )
, L
    ( Position 22 7 ) Colon
, L
    ( Position 22 9 )
    ( TokSym "git" )
, L
    ( Position 23 1 )
    ( Indent 2 )
, L
    ( Position 23 3 )
    ( TokSym "location" )
, L
    ( Position 23 11 ) Colon
, L
    ( Position 23 13 )
    ( TokSym "https" )
, L
    ( Position 23 18 ) Colon
, L
    ( Position 23 19 )
    ( TokOther "//" )
, L
    ( Position 23 21 )
    ( TokSym "github.com" )
, L
    ( Position 23 31 )
    ( TokOther "/" )
, L
    ( Position 23 32 )
    ( TokSym "creichert" )
, L
    ( Position 23 41 )
    ( TokOther "/" )
, L
    ( Position 23 42 )
    ( TokSym "dockerfile" )
, L
    ( Position 25 1 )
    ( Indent 0 )
, L
    ( Position 25 1 )
    ( TokSym "library" )
, L
    ( Position 26 1 )
    ( Indent 2 )
, L
    ( Position 26 3 )
    ( TokSym "exposed-modules" )
, L
    ( Position 26 18 ) Colon
, L
    ( Position 27 1 )
    ( Indent 6 )
, L
    ( Position 27 7 )
    ( TokSym "Data.Docker" )
, L
    ( Position 28 1 )
    ( Indent 2 )
, L
    ( Position 28 3 )
    ( TokSym "other-modules" )
, L
    ( Position 28 16 ) Colon
, L
    ( Position 29 1 )
    ( Indent 6 )
, L
    ( Position 29 7 )
    ( TokSym "Control.Monad.Writer" )
, L
    ( Position 30 1 )
    ( Indent 2 )
, L
    ( Position 30 3 )
    ( TokSym "build-depends" )
, L
    ( Position 30 16 ) Colon
, L
    ( Position 31 1 )
    ( Indent 6 )
, L
    ( Position 31 7 )
    ( TokSym "base" )
, L
    ( Position 31 12 )
    ( TokOther "==" )
, L
    ( Position 31 14 )
    ( TokSym "4." )
, L
    ( Position 31 16 )
    ( TokOther "*" )
, L
    ( Position 32 1 )
    ( Indent 2 )
, L
    ( Position 32 3 )
    ( TokSym "default-language" )
, L
    ( Position 32 19 ) Colon
, L
    ( Position 32 21 )
    ( TokSym "Haskell2010" )
, L
    ( Position 34 1 )
    ( Indent 0 )
, L
    ( Position 34 1 )
    ( TokSym "test-suite" )
, L
    ( Position 34 12 )
    ( TokSym "spec" )
, L
    ( Position 35 1 )
    ( Indent 2 )
, L
    ( Position 35 3 )
    ( TokSym "type" )
, L
    ( Position 35 7 ) Colon
, L
    ( Position 35 9 )
    ( TokSym "exitcode-stdio-1.0" )
, L
    ( Position 36 1 )
    ( Indent 2 )
, L
    ( Position 36 3 )
    ( TokSym "main-is" )
, L
    ( Position 36 10 ) Colon
, L
    ( Position 36 12 )
    ( TokSym "Spec.hs" )
, L
    ( Position 37 1 )
    ( Indent 2 )
, L
    ( Position 37 3 )
    ( TokSym "other-modules" )
, L
    ( Position 37 16 ) Colon
, L
    ( Position 38 1 )
    ( Indent 6 )
, L
    ( Position 38 7 )
    ( TokSym "Paths_dockerfile" )
, L
    ( Position 39 1 )
    ( Indent 2 )
, L
    ( Position 39 3 )
    ( TokSym "hs-source-dirs" )
, L
    ( Position 39 17 ) Colon
, L
    ( Position 40 1 )
    ( Indent 6 )
, L
    ( Position 40 7 )
    ( TokSym "test" )
, L
    ( Position 41 1 )
    ( Indent 2 )
, L
    ( Position 41 3 )
    ( TokSym "ghc-options" )
, L
    ( Position 41 14 ) Colon
, L
    ( Position 41 16 )
    ( TokSym "-Wall" )
, L
    ( Position 42 1 )
    ( Indent 2 )
, L
    ( Position 42 3 )
    ( TokSym "build-depends" )
, L
    ( Position 42 16 ) Colon
, L
    ( Position 43 1 )
    ( Indent 6 )
, L
    ( Position 43 7 )
    ( TokSym "base" )
, L
    ( Position 43 12 )
    ( TokOther "==" )
, L
    ( Position 43 14 )
    ( TokSym "4." )
, L
    ( Position 43 16 )
    ( TokOther "*" )
, L
    ( Position 44 1 )
    ( Indent 4 )
, L
    ( Position 44 5 )
    ( TokOther "," )
, L
    ( Position 44 7 )
    ( TokSym "dockerfile" )
, L
    ( Position 45 1 )
    ( Indent 4 )
, L
    ( Position 45 5 )
    ( TokOther "," )
, L
    ( Position 45 7 )
    ( TokSym "hspec" )
, L
    ( Position 46 1 )
    ( Indent 2 )
, L
    ( Position 46 3 )
    ( TokSym "default-language" )
, L
    ( Position 46 19 ) Colon
, L
    ( Position 46 21 )
    ( TokSym "Haskell2010" )
, L
    ( Position 47 1 ) EOF
]
