[ L
    ( Position 1 1 )
    ( Indent 0 )
, L
    ( Position 1 1 )
    ( TokSym "name" )
, L
    ( Position 1 5 ) Colon
, L
    ( Position 1 22 )
    ( TokSym "dockerfile" )
, L
    ( Position 2 1 )
    ( Indent 0 )
, L
    ( Position 2 1 )
    ( TokSym "version" )
, L
    ( Position 2 8 ) Colon
, L
    ( Position 2 22 )
    ( TokSym "0.1.0.1" )
, L
    ( Position 3 1 )
    ( Indent 0 )
, L
    ( Position 3 1 )
    ( TokSym "synopsis" )
, L
    ( Position 3 9 ) Colon
, L
    ( Position 3 22 )
    ( TokSym "A" )
, L
    ( Position 3 24 )
    ( TokSym "simple" )
, L
    ( Position 3 31 )
    ( TokSym "DSL" )
, L
    ( Position 3 35 )
    ( TokSym "for" )
, L
    ( Position 3 39 )
    ( TokSym "describing" )
, L
    ( Position 3 50 )
    ( TokSym "and" )
, L
    ( Position 3 54 )
    ( TokSym "generating" )
, L
    ( Position 3 65 )
    ( TokSym "Dockerfile" )
, L
    ( Position 3 76 )
    ( TokSym "containers" )
, L
    ( Position 3 87 )
    ( TokSym "in" )
, L
    ( Position 3 90 )
    ( TokSym "Haskell." )
, L
    ( Position 4 1 )
    ( Indent 0 )
, L
    ( Position 4 1 )
    ( TokSym "description" )
, L
    ( Position 4 12 ) Colon
, L
    ( Position 4 22 )
    ( TokSym "A" )
, L
    ( Position 4 24 )
    ( TokSym "simple" )
, L
    ( Position 4 31 )
    ( TokSym "DSL" )
, L
    ( Position 4 35 )
    ( TokSym "for" )
, L
    ( Position 4 39 )
    ( TokSym "describing" )
, L
    ( Position 4 50 )
    ( TokSym "and" )
, L
    ( Position 4 54 )
    ( TokSym "generating" )
, L
    ( Position 4 65 )
    ( TokSym "Dockerfile" )
, L
    ( Position 4 76 )
    ( TokSym "containers" )
, L
    ( Position 4 87 )
    ( TokSym "in" )
, L
    ( Position 4 90 )
    ( TokSym "Haskell." )
, L
    ( Position 5 1 )
    ( Indent 0 )
, L
    ( Position 5 1 )
    ( TokSym "license" )
, L
    ( Position 5 8 ) Colon
, L
    ( Position 5 22 )
    ( TokSym "MIT" )
, L
    ( Position 6 1 )
    ( Indent 0 )
, L
    ( Position 6 1 )
    ( TokSym "license-file" )
, L
    ( Position 6 13 ) Colon
, L
    ( Position 6 22 )
    ( TokSym "LICENSE" )
, L
    ( Position 7 1 )
    ( Indent 0 )
, L
    ( Position 7 1 )
    ( TokSym "author" )
, L
    ( Position 7 7 ) Colon
, L
    ( Position 7 22 )
    ( TokSym "Christopher" )
, L
    ( Position 7 34 )
    ( TokSym "Reichert" )
, L
    ( Position 8 1 )
    ( Indent 0 )
, L
    ( Position 8 1 )
    ( TokSym "maintainer" )
, L
    ( Position 8 11 ) Colon
, L
    ( Position 8 22 )
    ( TokSym "creichert07" )
, L
    ( Position 8 33 )
    ( TokOther "@" )
, L
    ( Position 8 34 )
    ( TokSym "gmail.com" )
, L
    ( Position 9 1 )
    ( Indent 0 )
, L
    ( Position 9 1 )
    ( TokSym "copyright" )
, L
    ( Position 9 10 ) Colon
, L
    ( Position 9 22 )
    ( TokOther "(" )
, L
    ( Position 9 23 )
    ( TokSym "c" )
, L
    ( Position 9 24 )
    ( TokOther ")" )
, L
    ( Position 9 26 )
    ( TokSym "2015" )
, L
    ( Position 9 31 )
    ( TokSym "Christopher" )
, L
    ( Position 9 43 )
    ( TokSym "Reichert" )
, L
    ( Position 9 52 )
    ( TokOther "<" )
, L
    ( Position 9 53 )
    ( TokSym "creichert07" )
, L
    ( Position 9 64 )
    ( TokOther "@" )
, L
    ( Position 9 65 )
    ( TokSym "gmail.com" )
, L
    ( Position 9 74 )
    ( TokOther ">" )
, L
    ( Position 10 1 )
    ( Indent 0 )
, L
    ( Position 10 1 )
    ( TokSym "category" )
, L
    ( Position 10 9 ) Colon
, L
    ( Position 10 22 )
    ( TokSym "Data" )
, L
    ( Position 11 1 )
    ( Indent 0 )
, L
    ( Position 11 1 )
    ( TokSym "build-type" )
, L
    ( Position 11 11 ) Colon
, L
    ( Position 11 22 )
    ( TokSym "Simple" )
, L
    ( Position 12 1 )
    ( Indent 0 )
, L
    ( Position 12 1 )
    ( TokSym "cabal-version" )
, L
    ( Position 12 14 ) Colon
, L
    ( Position 12 22 )
    ( TokOther ">=" )
, L
    ( Position 12 24 )
    ( TokSym "1.10" )
, L
    ( Position 14 1 )
    ( Indent 0 )
, L
    ( Position 14 1 )
    ( TokSym "library" )
, L
    ( Position 15 1 )
    ( Indent 2 )
, L
    ( Position 15 3 )
    ( TokSym "exposed-modules" )
, L
    ( Position 15 18 ) Colon
, L
    ( Position 15 24 )
    ( TokSym "Data.Docker" )
, L
    ( Position 16 1 )
    ( Indent 2 )
, L
    ( Position 16 3 )
    ( TokSym "other-modules" )
, L
    ( Position 16 16 ) Colon
, L
    ( Position 16 24 )
    ( TokSym "Control.Monad.Writer" )
, L
    ( Position 17 1 )
    ( Indent 2 )
, L
    ( Position 17 3 )
    ( TokSym "other-extensions" )
, L
    ( Position 17 19 ) Colon
, L
    ( Position 17 24 )
    ( TokSym "OverloadedStrings" )
, L
    ( Position 18 1 )
    ( Indent 2 )
, L
    ( Position 18 3 )
    ( TokSym "build-depends" )
, L
    ( Position 18 16 ) Colon
, L
    ( Position 18 24 )
    ( TokSym "base" )
, L
    ( Position 18 29 )
    ( TokOther "==" )
, L
    ( Position 18 32 )
    ( TokSym "4." )
, L
    ( Position 18 34 )
    ( TokOther "*" )
, L
    ( Position 19 1 )
    ( Indent 2 )
, L
    ( Position 19 3 )
    ( TokSym "default-language" )
, L
    ( Position 19 19 ) Colon
, L
    ( Position 19 24 )
    ( TokSym "Haskell2010" )
, L
    ( Position 21 1 )
    ( Indent 0 )
, L
    ( Position 21 1 )
    ( TokSym "test-suite" )
, L
    ( Position 21 12 )
    ( TokSym "spec" )
, L
    ( Position 22 1 )
    ( Indent 2 )
, L
    ( Position 22 3 )
    ( TokSym "build-depends" )
, L
    ( Position 22 16 ) Colon
, L
    ( Position 22 19 )
    ( TokSym "base" )
, L
    ( Position 22 24 )
    ( TokOther "==" )
, L
    ( Position 22 27 )
    ( TokSym "4." )
, L
    ( Position 22 29 )
    ( TokOther "*," )
, L
    ( Position 22 32 )
    ( TokSym "dockerfile" )
, L
    ( Position 22 42 )
    ( TokOther "," )
, L
    ( Position 22 44 )
    ( TokSym "hspec" )
, L
    ( Position 23 1 )
    ( Indent 2 )
, L
    ( Position 23 3 )
    ( TokSym "ghc-options" )
, L
    ( Position 23 14 ) Colon
, L
    ( Position 23 19 )
    ( TokSym "-Wall" )
, L
    ( Position 24 1 )
    ( Indent 2 )
, L
    ( Position 24 3 )
    ( TokSym "type" )
, L
    ( Position 24 7 ) Colon
, L
    ( Position 24 19 )
    ( TokSym "exitcode-stdio-1.0" )
, L
    ( Position 25 1 )
    ( Indent 2 )
, L
    ( Position 25 3 )
    ( TokSym "hs-source-dirs" )
, L
    ( Position 25 17 ) Colon
, L
    ( Position 25 19 )
    ( TokSym "test" )
, L
    ( Position 26 1 )
    ( Indent 2 )
, L
    ( Position 26 3 )
    ( TokSym "main-is" )
, L
    ( Position 26 10 ) Colon
, L
    ( Position 26 19 )
    ( TokSym "Spec.hs" )
, L
    ( Position 27 1 ) EOF
]
